#  Create dependabot.yml file for dependabot to create pull requests #3843
# Goal: Have dependabot make pull requests for vulnerabilities it finds

name: Dependabot pull requests

version: 1
updates:
  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    # Files stored in `app` directory
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"


# double check if there are packages or dependencies that swhouldn't be scanned/updated
